-- Migration 1 on Postgres: the end state of `init_db` (src/db/sqlite.rs) when
-- versioned migrations began. On SQLite, migration 1 is `init_db` itself.
--
-- It holds every table and named index `init_db` creates, and none of its
-- legacy DROPs, because no older Postgres database exists. Merged migration
-- files never change; a schema change is a new twin pair (docs/database.md).
-- `tests/postgres.rs` holds each version's shape to SQLite's, with these type
-- rules:
--
--   INTEGER                     BIGINT (timestamp_ms exceeds int4)
--   TEXT                        TEXT COLLATE "C" (SQLite's BINARY comparison)
--   BLOB                        BYTEA, except token_balances' two address
--                               columns, which hold 0x text despite the BLOB
--   INTEGER PRIMARY KEY
--     AUTOINCREMENT             BIGINT GENERATED BY DEFAULT AS IDENTITY
--   X''                         '\x'::bytea
--
-- `receipt_data` and `trace_data` stay TEXT, not JSONB: JSONB re-serializes,
-- and pages must get back the bytes that were written.

CREATE TABLE IF NOT EXISTS blocks (
    number BIGINT PRIMARY KEY,
    hash BYTEA NOT NULL UNIQUE,
    parent_hash BYTEA NOT NULL,
    timestamp BIGINT NOT NULL,
    timestamp_ms BIGINT NOT NULL DEFAULT 0,
    gas_used BIGINT NOT NULL DEFAULT 0,
    gas_limit BIGINT NOT NULL DEFAULT 0,
    miner BYTEA NOT NULL DEFAULT '\x'::bytea,
    tx_count BIGINT NOT NULL DEFAULT 0,
    base_fee TEXT COLLATE "C" NOT NULL DEFAULT '0',
    size BIGINT NOT NULL DEFAULT 0,
    extra_data TEXT COLLATE "C" NOT NULL DEFAULT '',
    epoch BIGINT NOT NULL DEFAULT 0,
    view BIGINT NOT NULL DEFAULT 0,
    proposer BYTEA NOT NULL DEFAULT '\x'::bytea,
    created_at BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_blocks_timestamp ON blocks (timestamp);

CREATE TABLE IF NOT EXISTS transactions (
    hash BYTEA PRIMARY KEY,
    block_number BIGINT NOT NULL,
    position BIGINT NOT NULL DEFAULT 0,
    from_addr BYTEA NOT NULL,
    to_addr BYTEA,
    status BIGINT NOT NULL DEFAULT 1,
    gas_used BIGINT NOT NULL DEFAULT 0,
    base_fee TEXT COLLATE "C" NOT NULL DEFAULT '0',
    contract_address BYTEA,
    fee_token BYTEA,
    fee_amount TEXT COLLATE "C" NOT NULL DEFAULT '0',
    input TEXT COLLATE "C" NOT NULL DEFAULT '0x',
    raw BYTEA,
    trace_data TEXT COLLATE "C",
    receipt_data TEXT COLLATE "C",
    timestamp BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_tx_from_block
    ON transactions (from_addr, block_number, position);
CREATE INDEX IF NOT EXISTS idx_tx_to_block
    ON transactions (to_addr, block_number, position);
CREATE INDEX IF NOT EXISTS idx_tx_block_position
    ON transactions (block_number, position);

CREATE TABLE IF NOT EXISTS token_metadata (
    address BYTEA PRIMARY KEY,
    name TEXT COLLATE "C" NOT NULL DEFAULT '',
    symbol TEXT COLLATE "C" NOT NULL DEFAULT '',
    decimals BIGINT NOT NULL DEFAULT 18,
    currency TEXT COLLATE "C" NOT NULL DEFAULT '',
    total_supply TEXT COLLATE "C" NOT NULL DEFAULT '0',
    logo_uri TEXT COLLATE "C" NOT NULL DEFAULT '',
    holder_count BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS transfer_events (
    -- BY DEFAULT, so a copy keeps its ids; an import must then setval the
    -- sequence to max(id).
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_hash BYTEA NOT NULL,
    block_number BIGINT NOT NULL,
    log_index BIGINT NOT NULL DEFAULT 0,
    token_addr BYTEA NOT NULL,
    from_addr BYTEA NOT NULL,
    to_addr BYTEA NOT NULL,
    amount TEXT COLLATE "C" NOT NULL,
    timestamp BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    UNIQUE (block_number, log_index)
);
CREATE INDEX IF NOT EXISTS idx_transfer_tx_hash ON transfer_events (tx_hash);
CREATE INDEX IF NOT EXISTS idx_transfer_token_block
    ON transfer_events (token_addr, block_number, log_index);
CREATE INDEX IF NOT EXISTS idx_transfer_from_block
    ON transfer_events (from_addr, block_number, log_index);
CREATE INDEX IF NOT EXISTS idx_transfer_to_block
    ON transfer_events (to_addr, block_number, log_index);

CREATE TABLE IF NOT EXISTS anchoring_events (
    tx_hash BYTEA NOT NULL,
    block_number BIGINT NOT NULL,
    log_index BIGINT NOT NULL,
    timestamp BIGINT NOT NULL DEFAULT 0,
    event TEXT COLLATE "C" NOT NULL,
    registry_id BIGINT NOT NULL,
    record_id BIGINT NOT NULL DEFAULT 0,
    caller BYTEA NOT NULL,
    UNIQUE (block_number, log_index)
);
CREATE INDEX IF NOT EXISTS idx_anchoring_registry
    ON anchoring_events (registry_id, block_number DESC, log_index DESC);

CREATE TABLE IF NOT EXISTS kv (
    key TEXT COLLATE "C" PRIMARY KEY,
    value TEXT COLLATE "C" NOT NULL DEFAULT '',
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS counters (
    name TEXT COLLATE "C" PRIMARY KEY,
    n BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS token_balances (
    -- Declared BLOB on SQLite, but every row holds 0x text.
    token_addr TEXT COLLATE "C" NOT NULL,
    holder_addr TEXT COLLATE "C" NOT NULL,
    balance TEXT COLLATE "C" NOT NULL DEFAULT '0',
    updated_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (token_addr, holder_addr)
);
CREATE INDEX IF NOT EXISTS idx_tb_holder ON token_balances (holder_addr);
-- The predicate is `HOLDING` in src/db/sqlite.rs: a partial index only serves
-- queries whose filter it provably implies. `holder_addr` is the holders page's
-- tie-break, so equal balances page in a stable order; SQLite's index stops at
-- the balance. `TRANSLATED` in tests/postgres.rs pins both definitions.
CREATE INDEX IF NOT EXISTS idx_tb_holding
    ON token_balances (token_addr, LENGTH(balance) DESC, balance DESC, holder_addr)
    WHERE balance NOT LIKE '-%';

CREATE TABLE IF NOT EXISTS genesis_balances (
    token_addr TEXT COLLATE "C" NOT NULL,
    holder_addr TEXT COLLATE "C" NOT NULL,
    balance TEXT COLLATE "C" NOT NULL,
    PRIMARY KEY (token_addr, holder_addr)
);

CREATE TABLE IF NOT EXISTS selector_names (
    selector TEXT COLLATE "C" PRIMARY KEY,
    signature TEXT COLLATE "C" NOT NULL DEFAULT '',
    fetched_at BIGINT NOT NULL DEFAULT 0
);
