apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: nvnmchain-explorer
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: explorer.nvnm.testnet.nvnmchain.io
  acmeProvider:
    authority: none
  tlsSecret:
    name: asia-east2-std.testnet.nvnmchain.io-wildcard-tls-secret
    namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: nvnmchain-explorer
spec:
  hostname: explorer.nvnm.testnet.nvnmchain.io
  prefix: /
  rewrite: ''
  service: nvnmchain-explorer:80
  timeout_ms: 30000
