# Version: 1.0.0
# Description:  This is a GitHub Actions workflow that runs unit tests and builds and pushes a Docker image to the Container Registry.
# Notes:
# Trigger
name: Docker Buildx - Standard

on:
  push:
    branches: ["main"]
    tags: ["v*"]

env:
  REGISTRY: ${{ vars.REGISTRY || format('ghcr.io/{0}', github.repository_owner) }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME || github.event.repository.name }}
  BUILD_ARGS: ${{ vars.BUILD_ARGS || '' }}
  BUILD_ARCH: ${{ vars.BUILD_ARCH || 'linux/amd64' }}

# Set concurrency for this workflow to cancel in-progress jobs if retriggered.
# The github.ref is only available when triggered by a PR so fall back to github.run_id for other cases.
# The github.run_id is unique for each run, giving each such invocation it's own unique concurrency group.
# Basically, if you push to a PR branch, jobs that are still running for that PR will be cancelled.
# But jobs started because of a merge to main or a release tag push are not cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:

  buildx:
    permissions:
      packages: write
      contents: read
    name: Docker Buildx
    runs-on: ${{ vars.RUNNER_SPEC || 'ubuntu-latest' }}
    steps:
      # Run a dummy shell command
      - name: Build docker image
        shell: bash
        run: echo "Build docker image - fast version"
      - uses: mantra-chain-tech/infra-github-actions-mantrachain/docker-buildx-v1@v1.0.0
        with:
          container_repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          build_context: "."
          build_args: ${{ env.BUILD_ARGS }}
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          arch: ${{ env.BUILD_ARCH}}
          docker_push: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
